# Generated by Django 2.2.5 on 2020-03-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200324_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfname', models.CharField(max_length=50)),
                ('blockname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfname', models.CharField(max_length=50)),
                ('friendname', models.CharField(max_length=50)),
            ],
        ),
    ]
