os: windows # => 1
language: python # => 2
    python: # => 3
      - "3.3"
      - "3.4"
      - "3.5"
      - "3.6"
      - "3.7"
      - "3.8"
    services: # => 4
      - sqlite
    env: # => 5
      -DJANGO=1.8 DB=sqlite
    install: # => 6
      - pip install -r requirements.txt
    script: # => 7
      - python manage.py test
